version: '3'

services:
  app:
    image: jigarsingh/merakitest:tagname
    build: ./Dockerfile
  
    deploy:
      replicas: 4
      update_config:
        parallelism: 4
      
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && app rspec "
       
    ports:
      - "3000:3000"
  
