version: '3'

services:
  app:
    image: jigarsingh/merakitest:tagname
    
    deploy:
      replicas: 4
      update_config:
        parallelism: 4
        delay: 10s
      restart_policy:
        condition: on-failure
      
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
  
